version: '3'

services:
  mariadb:
    image: 'bitnami/mariadb:10.5'
    ports:
      - '3306:3306'
    env_file: .mariadb.env
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  nginx:
    image: 'bitnami/nginx:1.19.10'
    ports:
      - '8080:8080'
    volumes:
      - './config/nginx/drupal.conf:/opt/bitnami/nginx/conf/server_blocks/drupal.conf'
      - 'drupal_data:/app/web/sites/default/files:ro'
    depends_on:
      - drupal
  drupal:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .drupal.env
    volumes:
      - 'drupal_data:/app/web/sites/default/files'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
  drupal_data:
